/* Firebird 3 metadata-only collection. Do not execute business procedures. */
SET LIST ON;
SET BLOB ALL;

SELECT TRIM(p.RDB$PROCEDURE_NAME) AS OBJECT_NAME,
       p.RDB$PROCEDURE_TYPE AS OBJECT_TYPE,
       p.RDB$PROCEDURE_SOURCE AS OBJECT_SOURCE
FROM RDB$PROCEDURES p
WHERE TRIM(p.RDB$PROCEDURE_NAME) IN (
  'PRECO_VENDA', 'WS_PRECOS', 'WS_PRECOS_ECOMMERCE', 'WS_PRECOS_VARIACAO'
)
ORDER BY p.RDB$PROCEDURE_NAME;

SELECT TRIM(pp.RDB$PROCEDURE_NAME) AS OBJECT_NAME,
       pp.RDB$PARAMETER_TYPE AS PARAMETER_TYPE,
       pp.RDB$PARAMETER_NUMBER AS PARAMETER_NUMBER,
       TRIM(pp.RDB$PARAMETER_NAME) AS PARAMETER_NAME,
       TRIM(pp.RDB$FIELD_SOURCE) AS FIELD_SOURCE,
       pp.RDB$NULL_FLAG AS NULL_FLAG,
       pp.RDB$DEFAULT_SOURCE AS DEFAULT_SOURCE
FROM RDB$PROCEDURE_PARAMETERS pp
WHERE TRIM(pp.RDB$PROCEDURE_NAME) IN (
  'PRECO_VENDA', 'WS_PRECOS', 'WS_PRECOS_ECOMMERCE', 'WS_PRECOS_VARIACAO'
)
ORDER BY pp.RDB$PROCEDURE_NAME, pp.RDB$PARAMETER_TYPE, pp.RDB$PARAMETER_NUMBER;

SELECT TRIM(d.RDB$DEPENDENT_NAME) AS DEPENDENT_NAME,
       d.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,
       TRIM(d.RDB$DEPENDED_ON_NAME) AS DEPENDED_ON_NAME,
       d.RDB$DEPENDED_ON_TYPE AS DEPENDED_ON_TYPE,
       TRIM(d.RDB$FIELD_NAME) AS FIELD_NAME
FROM RDB$DEPENDENCIES d
WHERE TRIM(d.RDB$DEPENDENT_NAME) IN (
  'PRECO_VENDA', 'WS_PRECOS', 'WS_PRECOS_ECOMMERCE', 'WS_PRECOS_VARIACAO'
)
ORDER BY d.RDB$DEPENDENT_NAME, d.RDB$DEPENDED_ON_NAME, d.RDB$FIELD_NAME;

SELECT TRIM(rf.RDB$RELATION_NAME) AS RELATION_NAME,
       rf.RDB$FIELD_POSITION AS FIELD_POSITION,
       TRIM(rf.RDB$FIELD_NAME) AS FIELD_NAME,
       TRIM(rf.RDB$FIELD_SOURCE) AS FIELD_SOURCE,
       rf.RDB$NULL_FLAG AS NULL_FLAG
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) = 'AGRUPAMENTOS'
ORDER BY rf.RDB$FIELD_POSITION;

QUIT;
