ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "isArchived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "archiveReason" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "financialProfile" JSONB;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "partnerTitles" JSONB;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "openTitlesTotal" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "overdueTitlesTotal" DOUBLE PRECISION DEFAULT 0;
CREATE INDEX IF NOT EXISTS "Client_isArchived_idx" ON "Client"("isArchived");
