ALTER TABLE "Client"
  ADD COLUMN IF NOT EXISTS "lastPurchaseDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastPurchaseValue" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "erpUpdatedAt" TIMESTAMP(3);
