import { Router } from "express";
import { z } from "zod";
import { prisma } from "../config/prisma.js";
import { authMiddleware } from "../middlewares/auth.js";
import { appUsageRateLimit } from "../middlewares/rateLimit.js";
import { getPlatformHealthSnapshot, PLATFORM_HEALTH_ROLES } from "../services/platformHealthService.js";
import { collectPlatformHealthHttp, projectAuditDataState } from "../services/platformHealthProjection.js";

const router = Router(); router.use(authMiddleware, appUsageRateLimit);
router.use((req, res, next) => PLATFORM_HEALTH_ROLES.has(String(req.user?.role).toLowerCase()) ? next() : res.status(403).json({ message: "Sem permissão para Saúde da Plataforma" }));
router.get("/snapshot", async (req, res) => { const days = z.coerce.number().pipe(z.union([z.literal(7), z.literal(30), z.literal(90)])).catch(7).parse(req.query.days); const result = await collectPlatformHealthHttp(() => getPlatformHealthSnapshot(days, req.query.refresh === "true")); res.status(result.status).json(result.body); });
const auditQuery = z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), client: z.string().trim().optional(), user: z.string().trim().optional(), origin: z.string().trim().optional(), partnerErp: z.string().trim().optional(), requestId: z.string().trim().optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional(), export: z.enum(["csv"]).optional() });
router.get("/audit", async (req, res) => { try { const q = auditQuery.parse(req.query); const where = { ...(q.client ? { client: { is: { OR: [{ name: { contains: q.client, mode: "insensitive" as const } }, { code: { contains: q.client, mode: "insensitive" as const } }] } } } : {}), ...(q.user ? { actorEmail: { contains: q.user, mode: "insensitive" as const } } : {}), ...(q.origin ? { origin: q.origin } : {}), ...(q.partnerErp ? { partnerErp: { contains: q.partnerErp, mode: "insensitive" as const } } : {}), ...(q.requestId ? { requestId: { contains: q.requestId, mode: "insensitive" as const } } : {}), ...(q.from || q.to ? { createdAt: { ...(q.from ? { gte: q.from } : {}), ...(q.to ? { lte: q.to } : {}) } } : {}) }; const take = q.export ? 5000 : q.pageSize; const [items, total] = await Promise.all([prisma.clientCodeAudit.findMany({ where, orderBy: { createdAt: "desc" }, skip: q.export ? 0 : (q.page - 1) * q.pageSize, take, include: { client: { select: { id: true, name: true, code: true } } } }), prisma.clientCodeAudit.count({ where })]); if (q.export) { const esc = (v: unknown) => `"${String(v ?? "").replace(/\"/g, '""')}"`; const csv = ["Data,Cliente,Antes,Depois,Origem,Usuario,Partner ERP,IP,RequestId", ...items.map(i => [i.createdAt.toISOString(), i.client.name, i.oldValue, i.newValue, i.origin, i.actorEmail, i.partnerErp, i.requestIp, i.requestId].map(esc).join(","))].join("\n"); res.setHeader("Content-Disposition", "attachment; filename=client-code-audit.csv"); return res.type("text/csv").send(csv); } res.json({ dataState: projectAuditDataState(total), items, pagination: { page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total / q.pageSize) } }); } catch { res.status(503).json({ dataState: "error", code: "PLATFORM_HEALTH_AUDIT_FAILED", message: "Não foi possível consultar a auditoria." }); } });
export default router;
