import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BellRing, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Database, Download, Gauge, History, Link2, RefreshCw, Search, ShieldCheck, Users } from "lucide-react";
import { Line } from "react-chartjs-2";
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Legend, Filler } from "chart.js";
import api from "../lib/apiClient";
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Legend, Filler);

type Snapshot = any;
const tabs = ["Visão geral", "Qualidade dos dados", "Integrações", "Auditoria", "Alertas"] as const;
const tones: Record<string, string> = { healthy: "border-emerald-200 bg-emerald-50 text-emerald-700", warning: "border-amber-200 bg-amber-50 text-amber-700", critical: "border-red-200 bg-red-50 text-red-700", neutral: "border-slate-200 bg-white text-slate-700" };
const fmtDuration = (ms?: number | null) => ms == null ? "—" : ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} s`;
const MetricCard = ({ title, value, icon: Icon = Gauge, tone = "neutral", updated, onClick }: any) => <button onClick={onClick} className={`group rounded-2xl border p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${tones[tone]}`}><div className="flex items-start justify-between"><span className="rounded-xl bg-white/80 p-2"><Icon size={20}/></span><ChevronRight size={17} className="opacity-50 transition group-hover:translate-x-1"/></div><div className="mt-4 text-2xl font-bold">{value ?? 0}</div><div className="mt-1 text-sm font-semibold">{title}</div><div className="mt-3 text-[11px] opacity-70">Atualizado {updated ? new Date(updated).toLocaleString("pt-BR") : "agora"} · Ver detalhes</div></button>;

export default function PlatformHealthPage() {
 const [tab,setTab]=useState<typeof tabs[number]>(tabs[0]); const [days,setDays]=useState<7|30|90>(7); const [data,setData]=useState<Snapshot>(); const [loading,setLoading]=useState(true); const [page,setPage]=useState(1); const [audit,setAudit]=useState<any>({items:[],pagination:{}}); const [filter,setFilter]=useState("");
 const load=async(force=false)=>{setLoading(true); try{setData((await api.get(`/platform-health/snapshot?days=${days}${force?"&refresh=true":""}`)).data)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[days]); useEffect(()=>{if(tab!=="Auditoria")return; const timer=setTimeout(()=>void api.get(`/platform-health/audit?page=${page}&pageSize=25&client=${encodeURIComponent(filter)}`).then(r=>setAudit(r.data)),250); return()=>clearTimeout(timer)},[tab,page,filter]);
 const overview=useMemo(()=>data?.overview?.metrics||{},[data]); const updated=data?.generatedAt;
 const go=(next:typeof tabs[number])=>setTab(next);
 const cards=[ ["Última sincronização ERP",data?.overview?.lastSync?.startedAt?new Date(data.overview.lastSync.startedAt).toLocaleString("pt-BR"):"Sem registro",History], ["Status da sincronização",data?.overview?.lastSync?.status||"indisponível",ShieldCheck], ["Tempo da última sincronização",fmtDuration(data?.overview?.lastSync?.durationMs),Clock3], ["Tempo médio",fmtDuration(data?.overview?.averageDurationMs),Gauge], ["Parceiros recebidos",overview.partnersReceived,Users], ["Parceiros atualizados",overview.partnersUpdated,Users], ["Clientes criados",overview.clientsCreated,Users], ["Clientes atualizados",overview.clientsUpdated,Users], ["Pedidos sincronizados",overview.ordersSynced,Link2], ["Pedidos com erro",overview.ordersError,AlertTriangle], ["Clientes alterados",overview.clientsUpdated,Users], ["Client.code alterados",overview.clientCodeChanges,History], ["Conflitos documentais",overview.documentConflicts,AlertTriangle], ["Fallback sem documento",overview.fallbackNoDocument,Database], ["Code Exact",overview.codeExact,CheckCircle2], ["Document Exact",overview.documentExact,CheckCircle2], ["Reject Conflict",overview.rejectConflict,AlertTriangle], ["Create No Safe Match",overview.createNoSafeMatch,Users] ];
 const qualityLabels:Record<string,string>={missingDocument:"Clientes sem documento",invalidDocument:"Clientes com documento inválido",duplicates:"Clientes duplicados",missingSeller:"Clientes sem vendedor",missingRegion:"Clientes sem região",missingPortfolio:"Clientes sem carteira",missingCity:"Clientes sem município",missingState:"Clientes sem UF",missingPhone:"Clientes sem telefone",missingEmail:"Clientes sem e-mail",financialProfilesOrphaned:"Parceiros financeiros órfãos",partnerTitlesInconsistent:"PartnerTitles inconsistentes",archived:"Clientes arquivados"};
 return <main className="mx-auto max-w-[1600px] space-y-6 p-4 pt-20 md:p-8 md:pt-8"><header className="overflow-hidden rounded-3xl bg-gradient-to-r from-brand-800 via-brand-700 to-emerald-700 p-6 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-emerald-200"><ShieldCheck size={18}/> Observabilidade executiva</div><h1 className="mt-2 text-3xl font-bold">Saúde da Plataforma</h1><p className="mt-2 max-w-3xl text-sm text-white/75">Estado operacional do CRM, integrações ERP e qualidade dos dados, sem interferir nas regras de negócio.</p></div><button onClick={()=>void load(true)} className="flex items-center gap-2 rounded-xl bg-white/15 px-4 py-2 text-sm font-semibold hover:bg-white/25"><RefreshCw className={loading?"animate-spin":""} size={17}/>Atualizar</button></div><div className="mt-5 flex flex-wrap gap-2">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===x?"bg-white text-brand-800":"bg-white/10 text-white hover:bg-white/20"}`}>{x}</button>)}</div></header>
 <div className="flex items-center justify-between"><p className="text-xs text-slate-500">Atualização: {updated?new Date(updated).toLocaleString("pt-BR"):"carregando..."} {data?.cacheHit&&"· cache"}</p>{tab!=="Auditoria"&&<div className="flex rounded-xl border bg-white p-1">{([7,30,90] as const).map(x=><button key={x} onClick={()=>setDays(x)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${days===x?"bg-brand-700 text-white":"text-slate-500"}`}>{x} dias</button>)}</div>}</div>
 {tab==="Visão geral"&&<><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{cards.map(([title,value,icon]:any)=><MetricCard key={title} title={title} value={value} icon={icon} updated={updated} tone={String(title).includes("erro")||String(title).includes("Conflito")||String(title).includes("Reject")?"critical":String(title).includes("Status")&&value==="success"?"healthy":"neutral"} onClick={()=>go(String(title).includes("sincronização")||String(title).includes("Tempo")||String(title).includes("Pedidos")?"Integrações":String(title).includes("Client.code")?"Auditoria":"Qualidade dos dados")}/>)}</section><Trend data={data}/></>}
 {tab==="Qualidade dos dados"&&<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{Object.entries(qualityLabels).map(([key,label])=><MetricCard key={key} title={label} value={data?.quality?.[key]||0} icon={Database} updated={updated} tone={data?.quality?.[key]>0?"warning":"healthy"} onClick={()=>window.location.assign(`/clientes?healthFilter=${key}`)}/>)}</section>}
 {tab==="Integrações"&&<Integration data={data} updated={updated}/>} {tab==="Alertas"&&<Alerts alerts={data?.alerts||[]}/>} {tab==="Auditoria"&&<Audit audit={audit} filter={filter} setFilter={setFilter} page={page} setPage={setPage}/>}</main>
}
function Trend({data}:any){const points=data?.trends?.syncDuration||[]; return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold text-slate-800">Tendência do tempo de sincronização</h2><div className="h-64"><Line options={{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}} data={{labels:points.map((p:any)=>p.date),datasets:[{data:points.map((p:any)=>p.value/1000),borderColor:"#15803d",backgroundColor:"rgba(21,128,61,.12)",fill:true,tension:.35}]}}/></div></section>}
function Integration({data,updated}:any){const i=data?.integration||{}; return <><section className="grid gap-4 md:grid-cols-3 lg:grid-cols-6"><MetricCard title="ERP conectado" value={i.connected?"Sim":"Não"} icon={Link2} tone={i.connected?"healthy":"critical"} updated={updated}/><MetricCard title="Latência" value={fmtDuration(i.latencyMs)} icon={Clock3} updated={updated}/><MetricCard title="Tempo médio" value={fmtDuration(i.averageDurationMs)} icon={Gauge} updated={updated}/><MetricCard title="Taxa de sucesso" value={`${((i.successRate||0)*100).toFixed(1)}%`} tone="healthy" updated={updated}/><MetricCard title="Taxa de erro" value={`${((i.errorRate||0)*100).toFixed(1)}%`} tone={i.errorRate?"critical":"healthy"} updated={updated}/><MetricCard title="Retries" value={i.retries||0} updated={updated}/></section><section className="overflow-hidden rounded-2xl border bg-white"><h2 className="p-5 font-bold">Histórico das últimas sincronizações</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Início","Escopo","Status","Tempo","Registros","Erro / warning"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{(i.recentRuns||[]).map((r:any)=><tr className="border-t" key={r.id}><td className="p-3">{new Date(r.startedAt).toLocaleString("pt-BR")}</td><td className="p-3">{r.scope}</td><td className="p-3 font-semibold">{r.status}</td><td className="p-3">{fmtDuration(r.durationMs)}</td><td className="p-3">{r.syncedCount}</td><td className="max-w-xs truncate p-3 text-red-600">{r.errorMessage||"—"}</td></tr>)}</tbody></table></div></section></>}
function Alerts({alerts}:any){return <section className="space-y-3">{!alerts.length&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center text-emerald-700"><CheckCircle2 className="mx-auto mb-2"/>Nenhum alerta ativo.</div>}{alerts.map((a:any)=><details key={a.id} className={`rounded-2xl border p-5 ${tones[a.severity]}`}><summary className="flex cursor-pointer items-center gap-3 font-bold"><BellRing size={20}/><span className="flex-1">{a.title}</span><span className="rounded-full bg-white/70 px-3 py-1 text-xs">{a.value}</span></summary><p className="mt-3 pl-8 text-sm">{a.detail}</p></details>)}</section>}
function Audit({audit,filter,setFilter,page,setPage}:any){const download=()=>api.get(`/platform-health/audit?export=csv&client=${encodeURIComponent(filter)}`,{responseType:"blob"}).then(r=>{const a=document.createElement("a");a.href=URL.createObjectURL(r.data);a.download="client-code-audit.csv";a.click();URL.revokeObjectURL(a.href)}); return <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap items-center gap-3 p-4"><div className="flex flex-1 items-center gap-2 rounded-xl border px-3"><Search size={17}/><input value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}} className="w-full py-2 outline-none" placeholder="Filtrar por cliente ou código"/></div><button onClick={download} className="flex items-center gap-2 rounded-xl bg-brand-700 px-4 py-2 text-sm font-bold text-white"><Download size={17}/>Exportar CSV</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Data","Cliente","Antes","Depois","Origem","Usuário","Partner ERP","IP","RequestId"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{audit.items.map((x:any)=><tr className="border-t" key={x.id}><td className="whitespace-nowrap p-3">{new Date(x.createdAt).toLocaleString("pt-BR")}</td><td className="p-3 font-semibold">{x.client.name}</td><td className="p-3">{x.oldValue||"—"}</td><td className="p-3">{x.newValue||"—"}</td><td className="p-3">{x.origin}</td><td className="p-3">{x.actorEmail||"Sistema"}</td><td className="p-3">{x.partnerErp||"—"}</td><td className="p-3">{x.requestIp||"—"}</td><td className="p-3 font-mono text-xs">{x.requestId}</td></tr>)}</tbody></table></div><div className="flex items-center justify-end gap-3 border-t p-4 text-sm"><span>{audit.pagination.total||0} registros</span><button disabled={page<=1} onClick={()=>setPage((x:number)=>x-1)}><ChevronLeft/></button><strong>{page} / {audit.pagination.totalPages||1}</strong><button disabled={page>=audit.pagination.totalPages} onClick={()=>setPage((x:number)=>x+1)}><ChevronRight/></button></div></section>}
